# Вводим переменные с клавиатуры
name = input("Введите ваше имя: ")
age = int(input("Введите ваш возраст: "))
city = input("Введите ваш город проживания: ")
sdfsd = input("Введите ваш город проживания: ")
qwrq = input("Введите ваш город проживания: ")

# Выводим информацию
print("Hi, i'm", name)
print("I'm", age, "years old")
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
print("I live in", city)
